version: '3.8'
services:
  gateway:
    build: ./gateway
    image: server_gateway
    container_name: server_gateway_container
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - SHAREIT_SERVER_URL=http://server:9090

  server:
    build: ./server
    image: server_shareit
    container_name: server_shareit_conteiner
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/shareit
      - DB_NAME=shareit
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - DB_HOST=postgres
      - DB_PORT=6541

  db:
    image: postgres:13.7-alpine
    container_name: postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root