CREATE TABLE IF NOT EXISTS users (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name varchar,
    email varchar,
    CONSTRAINT email UNIQUE (email)


);
CREATE TABLE IF NOT EXISTS items (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    name varchar,
    description varchar,
    available boolean,
    owner integer not null references users (id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS booking (
    id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
    start_booking DATETIME,
    end_booking DATETIME,
    item INTEGER NOT NULL REFERENCES items (id) ON DELETE CASCADE,
    booker INTEGER NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    status varchar NOT NULL
);